{
 "title": "Sei Node Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Cosmos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Num Txns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "tendermint_consensus_num_txs", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Percentage of Missed blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "cosmos_validators_missed_blocks / 10000",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "# Jailed validators",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(cosmos_validators_jailed) by (instance)"
    }
   ]
  },
  { "title": "Tendermint Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Consensus Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "tendermint_consensus_height", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Consensus block interval (secs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(tendermint_consensus_block_interval_seconds_bucket[5m])) by (le)) ",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(tendermint_consensus_block_interval_seconds_bucket[5m])) by (le)) ",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(tendermint_consensus_block_interval_seconds_bucket[5m])) by (le)) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mempool size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "tendermint_mempool_size", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Mempool TX Size (KB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(.99, rate(tendermint_mempool_tx_size_bytes_bucket[5m])) / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Missing Validators",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators_power",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "P2P pending tx bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "tendermint_p2p_peer_pending_send_bytes"
    }
   ]
  },
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Total IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    { "expr": "node_disk_io_now" }
   ]
  },
  {
   "title": "IO Writes vs Reads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "irate(node_disk_write_time_seconds_total[30s]) / irate(node_disk_io_time_seconds_total[30s])",
     "legendFormat": "writes - {{instance}}"
    },
    {
     "expr": "irate(node_disk_read_time_seconds_total[30s]) / irate(node_disk_io_time_seconds_total[30s])",
     "legendFormat": "reads {{instance}}"
    }
   ]
  },
  {
   "title": "CPU time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total[1m])) by (mode)"
    },
    {}
   ]
  },
  {
   "title": "Node RX / TX bytes (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[1m]) / 1000000",
     "legendFormat": "rx {{instance}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total[1m]) / 1000000",
     "legendFormat": "tx {{instance}}"
    }
   ]
  },
  {
   "title": "FD limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "open fds {{instance}}" },
    { "expr": "process_max_fds", "legendFormat": "max fds {{instance}}" }
   ]
  }
 ]
}